version: 2

sources:
  - name: techstore
    database: techstore-456412
    schema: techstore
    tables:
      - name: produits
      - name: clients
      - name: dates
      - name: regions
      - name: ventes
